- name: Deploy and start paisa container
  community.docker.docker_compose_v2:
    project_name: "paisa"
    state: present
    definition:
      services:
        paisa:
          container_name: "paisa"
          image: "{{ paisa_image }}"
          pull_policy: always
          restart: unless-stopped
          volumes:
            - "{{ paisa_data_dir }}:/root/Documents/paisa:rw"
      networks:
        default:
          name: "{{ homelab_network_name }}"
          external: true
