- name: Ensure Frigate config directory exists
  become: true
  become_user: root
  ansible.builtin.file:
    path: "{{ frigate_config_file | dirname }}"
    state: directory
    recurse: true
    mode: "775"
    owner: "{{ ansible_user_id }}"
    group: docker

- name: Copy Frigate config file
  become: true
  become_user: root
  ansible.builtin.copy:
    src: frigate.yaml
    dest: "{{ frigate_config_file }}"
    mode: "775"
    owner: "{{ ansible_user_id }}"
    group: docker

- name: Ensure Frigate project directory exists
  become: true
  become_user: root
  ansible.builtin.file:
    path: "{{ frigate_project_directory }}"
    state: directory
    recurse: true
    mode: "775"
    owner: "{{ ansible_user_id }}"
    group: docker

- name: Copy Frigate docker compose file
  become: true
  become_user: root
  ansible.builtin.template:
    backup: true
    src: docker-compose.yml
    dest: "{{ frigate_project_directory }}/docker-compose.yml"
    mode: "775"
    owner: "{{ ansible_user_id }}"
    group: docker

- name: Deploy Frigate container
  community.docker.docker_compose_v2:
    project_name: "{{ frigate_project_name }}"
    project_src: "{{ frigate_project_directory }}"
    state: present
    remove_orphans: true
    wait: true
