- name: Server setup
  hosts: local
  vars_files: ["./vars/main.yml"]

  roles:
    - role: setup
      vars:
        ansible_become_password: '{{ lookup("env", "ANSIBLE_BECOME_PASSWORD") }}' # noqa var-naming[no-role-prefix]
        setup_backup_user: "backupuser"
        setup_backup_ssh_key_path: "/home/backupuser/.ssh/backup"
        setup_backup_ssh_key_content: "{{ backup_ssh_key }}"
        setup_backup_ssh_key_public_content: "{{ backup_ssh_key_public }}"
        setup_backup_ssh_host: "{{ backup_ssh_user }}@{{ backup_ssh_host }}:{{ backup_ssh_port }}"

    - role: borgbase.ansible_role_borgbackup
      become: true
      borg_encryption_passphrase: "{{ backup_encryption_passphrase }}"
      borg_repository: ssh://{{ backup_ssh_user }}@{{ backup_ssh_host }}:{{ backup_ssh_port }}/{{ backup_ssh_directory }}
      borg_ssh_command: "ssh -i /home/backupuser/.ssh/backup"
      borg_ssh_key_name: "backup"
      borg_user: "backupuser"
      borg_group: "backupuser"
      borgmatic_timer: systemd
      borgmatic_timer_hour: 1
      borgmatic_timer_minute: 0
      borg_retention_policy:
        keep_hourly: 6
        keep_daily: 3
        keep_weekly: 2
      borg_source_directories: ["/media/homelab/data"]
      borgmatic_hooks:
        sqlite_databases:
          - name: frigate
            path: /media/homelab/data/frigate/config/frigate.db
      vars:
        ansible_become_password: '{{ lookup("env", "ANSIBLE_BECOME_PASSWORD") }}'

    - role: cloudflared
      vars:
        homelab_network_name: cloudflared
        cloudflared_token: "{{ cloudflared_tunnel_token }}"

    - role: frigate
      vars:
        homelab_network_name: cloudflared
        ansible_become_password: '{{ lookup("env", "ANSIBLE_BECOME_PASSWORD") }}' # noqa var-naming[no-role-prefix]
        frigate_rtsp_stream1: "rtsp://admin:{{ security_door_camera_password }}@{{ security_door_camera_address }}:554/stream1"
        frigate_rtsp_stream2: "rtsp://admin:{{ security_door_camera_password }}@{{ security_door_camera_address }}:554/stream2"
        frigate_mqtt_username: "{{ mqtt_username }}"
        frigate_mqtt_password: "{{ mqtt_password }}"
        frigate_project_directory: /home/sagnik/frigate
        frigate_image: ghcr.io/blakeblackshear/frigate:0.17.1-rocm
        frigate_data_dir: /media/homelab/data/frigate
        frigate_config_file: /media/homelab/data/frigate/config/config.yml

    - role: paisa
      vars:
        homelab_network_name: cloudflared
        paisa_image: ananthakumaran/paisa:latest
        paisa_data_dir: /media/homelab/data/paisa

    - role: home_assistant
      vars:
        ansible_become_password: '{{ lookup("env", "ANSIBLE_BECOME_PASSWORD") }}' # noqa var-naming[no-role-prefix]
        homelab_network_name: cloudflared
        home_assistant_data_dir: /media/homelab/data/home_assistant
        home_assistant_image: ghcr.io/home-assistant/home-assistant:stable
        mosquitto_data_dir: /media/homelab/data/mosquitto
        mosquitto_image: eclipse-mosquitto:latest
        mosquitto_username: "{{ mqtt_username }}"
        mosquitto_password: "{{ mqtt_password }}"
        mosquitto_pwfile: "{{ mqtt_password_file }}"
