services:
  frigate:
    container_name: "{{ frigate_container_name }}"
    image: "{{ frigate_image }}"
    restart: always
    shm_size: "150mb"
    privileged: true
    mem_swappiness: 0
    volumes:
      - /dev:/dev
      - /etc/localtime:/etc/localtime:ro
      - "{{ frigate_data_dir }}/config:/config:rw"
      - "{{ frigate_data_dir }}/data:/media/frigate:rw"
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "8971:8971"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    environment:
      - "FRIGATE_OPENAI_API_KEY={{ frigate_openai_key }}"
      - "FRIGATE_DOOR_CAMERA_RTSP_STREAM1={{ frigate_rtsp_stream1 }}"
      - "FRIGATE_DOOR_CAMERA_RTSP_STREAM2={{ frigate_rtsp_stream2 }}"
      - "LIBVA_DRIVER_NAME=radeonsi"
      - "HSA_OVERRIDE_GFX_VERSION=9.0.0"
    devices:
      - "/dev/apex_0:/dev/apex_0"
      - "/dev/dri:/dev/dri"
      - "/dev/kfd:/dev/kfd"

networks:
  default:
    name: "{{ frigate_network_name }}"
    external: true
