- name: Setup rclone
  ansible.builtin.include_role:
    name: stefangweichinger.ansible_rclone
    apply:
      become: true
  vars:
    install_manpages: false
    rclone_configs:
      - name: gdrive
        properties:
          type: "drive"
          scope: "drive"
          client_id: "{{ google_client_id }}"
          client_secret: "{{ google_client_secret }}"
          token: " {{ google_auth_token }}"
    rclone_mounts:
      - name: my-app
        remote_name: gdrive
        remote_path: "/backup_lserver_paisa"
        local_path: "/media/homelab/data/paisa"
        local_path_mode: "775"
        local_path_owner: root
        local_path_group: docker
        auto_mount: true
        extra_args: ""

- name: Restart rclone # noqa: no-handler
  when: setup_rclone_config.changed
  ansible.builtin.systemd:
    name: rclone.service
    state: restarted
